//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int IDInventory { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int QuantityInStock { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
