//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int IDSupplier { get; set; }
        public string NameSupplier { get; set; }
        public string PhoneSupplier { get; set; }
        public string AddressSupplier { get; set; }
    }
}
